# ruby

source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "just-the-docs"

# Desarrollo Local
# gem "webrick"

# GitHub Pages
gem "jekyll-remote-theme"

# Plugins opcionales (mantener en ambos entornos)
gem "jekyll-sitemap"
gem "jekyll-seo-tag"

# Grupo de plugins de Jekyll (mantener en ambos entornos)
group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
# GitHub Pages 
gem "github-pages", group: :jekyll_plugins
end

