source "https://rubygems.org"

gem "jekyll"
gem "just-the-docs"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "webrick"

# Windows compatibility
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :jekyll_plugins do
  gem "jekyll-feed"
end