source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "just-the-docs"
gem "webrick"

# Plugins opcionales
gem "jekyll-sitemap"
gem "jekyll-seo-tag"

# Grupo de plugins de Jekyll
group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end 